name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Install dependencies
      # run: sudo apt-get update && sudo apt-get install -y cmake g++-11
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_CXX_STANDARD=11
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: ctest --test-dir build || true
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
